[workspace]
members = ["programs/*", "rust-client", "dynamic-amm-quote"]
resolver = "2"

[workspace.package]
version = "0.0.3"
authors = ["Andrew"]
edition = "2021"

[workspace.dependencies]
anchor-lang = "1.0.0"
anchor-spl = "1.0.0"
anchor-client = "1.0.0"

[patch.crates-io]
spl-stake-pool = { git = "https://github.com/solana-program/stake-pool.git", rev = "36096981884e390565fae235b916e8ccc05a749c", features = [
    "no-entrypoint",
] }
