[package]
name = "mercurial-amm"
version = "0.4.9"
description = "Created with Anchor"
edition = "2021"
license = "MIT"
readme = "README.md"

[lib]
crate-type = ["cdylib", "lib"]
name = "amm"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
staging = []
test-bpf = []
test-bpf-snapshot = []

[profile.release]
overflow-checks = true

[dependencies]
anchor-lang = "0.26"
anchor-spl = "0.26"
#mercurial-vault = { version = "0.4.7", features = ["cpi"] }
mercurial-vault = { path = "../../../vault-sdk/programs/vault" }
spl-token-swap = { version = "3.0.0", features = ["no-entrypoint"] }
#meteora-stable-swap-math = "1.8.1"
#meteora-stable-swap-client = "1.8.1"
meteora-stable-swap-math = { path = "../../../stable-swap/stable-swap-math", package = "stable-swap-math" }
meteora-stable-swap-client = { path = "../../../stable-swap/stable-swap-client", package = "stable-swap-client" }
meteora-marinade-sdk = { version = "0.1.0", features = ["cpi"] }
spl-stake-pool = { version = "0.6.4", features = ["no-entrypoint"] }
anyhow = "1.0.71"

[dev-dependencies]
solana-program-test = "~1.14.17"
solana-sdk = "~1.14.17"
solana-account-decoder = "~1.14.17"
solana-client = "~1.14.17"
spl-associated-token-account = { version = "1.1.2", features = ["no-entrypoint"] }
serde_json = "1.0.95"
serde = "1.0.159"
bincode = "1.3.3"